### ISSUE TITLE
Error: Could not find or load main class efi.efiscen.guiFX.Main

### ISSUE THREAD

**Issue by makbuk** [EuropeanForestInstitute/efiscen#1]
I want to try the model work on the Utopia data, before I use my data, but I ran into a problem, I will be grateful for any help. 
I download Compiled version of model **EFISCEN version 4.1** from link:
http://www.efi.int/portal/virtual_library/databases/efiscen/model_availability/
http://www.efi.int/files/attachments/publications/efiscen/efiscen41_dist_05_2016.zip

When I try to open it in Ubuntu 16.04 the graphical user interface (GUI) of EFISCEN by typing in terminal:
**java -jar Efiscen_guifx.jar** 
I get error:
**Error: Could not find or load main class efi.efiscen.guiFX.Main**
When I try:
**java -Duser.language=US -Duser.region=US –jar Efiscen_guifx.jar**
I get error:
**Error: Could not find or load main class –jar**

How can I fix this?

**Comment by sergoefi** [comment]
Hi Maksym. Sorry, could not repeat your problem. I downloaded zip on my Ubuntu 14.04 and then provided in terminal the first command: java -jar Efiscen_guifx.jar was able to run the app. Could you give me more details on your environment: java version, localisation setting etc... WBR Sergey

**Comment by makbuk** [comment]
Hi Sergey, thanks for the response.
I try to run Efiscen_guifx.jar from folder /home/makbuk/projects/EFISCEN/dist_05_2016/
My environment:
**java -version**
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

I use English localization of Ubuntu
**locale**
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=uk_UA.UTF-8
LC_TIME=uk_UA.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=uk_UA.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=uk_UA.UTF-8
LC_NAME=uk_UA.UTF-8
LC_ADDRESS=uk_UA.UTF-8
LC_TELEPHONE=uk_UA.UTF-8
LC_MEASUREMENT=uk_UA.UTF-8
LC_IDENTIFICATION=uk_UA.UTF-8
LC_ALL=

**echo $JAVA_HOME**
/usr/lib/jvm/java-8-openjdk-amd64/
**echo $CLASSPATH**
JAVA_HOME/lib/:
**echo $PATH**
/usr/lib/jvm/java-8-openjdk-amd64//bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by makbuk** [comment]
Sergey, do not look for solutions, it looks like the program started to run.
It starts from **java -jar Efiscen_guifx.jar** It still does not work **java -Duser.language=US -Duser.region=US –jar Efiscen_guifx.jar** but I think it's not important.

**Comment by makbuk** [comment]
Last steps that I done:

**sudo apt-get install openjfx
sudo apt-get install openjfx-source**

**sudo nano ~/.bashrc**

add text to the end of the file:

_#ADD JAVA environment variables
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
export CLASSPATH=JAVA_HOME/lib/:$CLASSPATH
export PATH=$JAVA_HOME/bin/:$PATH_

And then reboot the system.

Sergey, thanks again for responding.

**Comment by sergoefi** [comment]
Hi Maksym. Nice to know, that it works now. It must be CLASSPATH problem. Another way to run is to specify CLASSPATH by using -cp option: java -cp Efiscen_guifx.jar efi.efiscen.guiFX.Main for GUI and java -cp Efiscen_guifx.jar efi.efiscen.cli.EfiscenCLI for command line without GUI. The second command you tried with -Duser options is for computers with different regional settings from US to avoid problem with CSV separators ;) Have fun with app.

**Comment by sergoefi** [comment]
The reason of issue was absence of JavaFX installed.
