### ISSUE TITLE
export to csv

### ISSUE THREAD

**Issue by TomPohys** [EuropeanForestInstitute/efiscen#3]
I working on non-english Windows 10 (Czech), where as decimal character is comma, not dot. If I export the results into CSV, there are comma for column and comma for decimal separator.

I try to change setting (from comma to dot as decimal symbol) in Windows in "Region & language" settings, but no change in export. 

Can you please help me to solve this problem?

**Comment by sergoefi** [comment]
Hi Tom. Changing regional settings on Windows does not affect the EFISCEN output. Check the manual please. There are instruction how to run EFISCEN on system with locales different from EN/US. Then you will have an output with comma as the delimiter and dot as a decimal symbol. Please let me know how it works. WBR Sergey

**Comment by TomPohys** [comment]
Yes, it works. Thank you
