### ISSUE TITLE
valid defcut for more forest type? 

### ISSUE THREAD

**Issue by vpechanec** [EuropeanForestInstitute/efiscen#4]
Hi,
I need to set up a more complicated wood removal demand scenario.
Please, how does look like a valid file (defcut) for 2 different forest type? (I want a different scenario for each FT).
In all manuals, I found a sample only for setting one scenario for all FTs (0 0 0 0), any of my modifications of file for multiple FT (0 0 1 0 and 0 0 2 0) ends by not adding to the scenario.
Thank you
Vilem

**Comment by sergoefi** [comment]
Hi Vilem,
Please try provide the input for your scenario like this:
-------------------------------------
Wood demand scenario file
Different demand by FT
Vil
2
Comments line 0 0 0 0 means for all
0,0,1,0,0,0,2,0
Step,FellFT1,ThinFT1,FellFT2,ThinFT2,
1,45113.36988,19334.30138,1000,1000
2,46988.5722,20137.95951,1000,1000
3,47443.57052,20332.9588,1000,1000
4,47898.56885,20527.95808,1000,1000
1000,47898.56885,20527.95808,1000,1000
---------------------------------------------
let us know how it works

**Comment by vpechanec** [comment]
Hello,

This example works at 100%. I modified for my conditions. All works!
My mistake was in row with steps, fell, thin, I wrote parameters for next
FT to a new row.

Thank you very much
Vilem Pechanec

út 19. 2. 2019 v 11:24 odesílatel sergoefi <notifications@github.com>
napsal:
